# Generated by Django 5.0.1 on 2024-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_mensaje_archivo_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensaje",
            name="contenido",
            field=models.TextField(blank=True),
        ),
    ]
